#!/usr/bin/env python3
"""Write the previous / contents / next links at the foot of every book page.

The reading order is `docs/SUMMARY.md`, and nothing else: every `[title](path)`
link in it is a page, in the order it appears. Run this after adding, removing
or moving a page (`make docs-nav`); it replaces the footer it wrote last time
and touches nothing else. `--check` exits 1 if any footer is out of date.
"""

import os
import re
import sys

DOCS = os.path.dirname(os.path.abspath(__file__))
SUMMARY = os.path.join(DOCS, "SUMMARY.md")
CONTENTS = os.path.join(DOCS, "book", "README.md")
MARK = "<!-- nav: generated by docs/nav.py, do not edit by hand -->"


def pages():
    text = open(SUMMARY, encoding="utf-8").read()
    found = []
    for title, path in re.findall(r"\[([^\]]+)\]\(([^)#\s]+\.md)\)", text):
        full = os.path.normpath(os.path.join(DOCS, path))
        if full != SUMMARY and full not in (p for _, p in found):
            found.append((title, full))
    return found


def link(title, target, source):
    rel = os.path.relpath(target, os.path.dirname(source))
    return f"[{title}]({rel})"


def footer(i, order):
    here = order[i][1]
    parts = []
    if i > 0:
        parts.append("← " + link(*order[i - 1], here))
    nxt = order[i + 1][1] if i + 1 < len(order) else None
    if CONTENTS not in (here, nxt):
        parts.append(link("Contents", CONTENTS, here))
    if i + 1 < len(order):
        title, target = order[i + 1]
        parts.append("**Next: " + link(title, target, here) + " →**")
    return f"{MARK}\n\n---\n\n{' · '.join(parts)}\n"


def main():
    check = "--check" in sys.argv
    order = pages()
    stale = []
    for i, (_, path) in enumerate(order):
        text = open(path, encoding="utf-8").read()
        body = text.split(MARK)[0].rstrip("\n")
        new = body + "\n\n" + footer(i, order)
        if new != text:
            stale.append(os.path.relpath(path, DOCS))
            if not check:
                open(path, "w", encoding="utf-8").write(new)
    if check and stale:
        print("page footers out of date; run `make docs-nav`:", *stale, sep="\n  ")
        return 1
    if not check:
        print(f"{len(order)} pages, {len(stale)} footers written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
