#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Stage the book for mdBook: `make docs-site` runs this, then `mdbook build`.

The book is written to read well on GitHub, so its links are repository
paths: the first page is the root README, chapters link to
`../../spec/protocol.md`, and every page ends in a footer `docs/nav.py`
wrote. mdBook wants every page under one source folder and draws its own
previous / next links. So this copies the pages into `target/book-src`
and, on the way:

* the README becomes the book's first page (every README is staged as
  `index.md`, the name mdBook serves it under), and its `docs/book/…` links
  point at the copies beside it;
* a link to anything that is not a book page — source code, an example,
  SECURITY.md — becomes a link to that file on GitHub;
* the nav footer is dropped.

The Markdown in `docs/` is never changed; this only writes the copy.
"""

import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
OUT = os.path.join(ROOT, "target", "book-src")
REPO = "https://github.com/mhmtskrc2/zygo"
MARK = "<!-- nav: generated by docs/nav.py, do not edit by hand -->"
LINK = re.compile(r"(\]\()([^)\s]+)(\))")


def staged(src):
    """Where a repository file lands in the staged book, or None if it is
    not a book page."""
    rel = os.path.relpath(src, ROOT)
    if rel == "README.md":
        return os.path.join(OUT, "index.md")
    if rel.startswith("docs" + os.sep):
        page = os.path.join(OUT, os.path.relpath(src, DOCS))
        # mdBook serves a README as index.html but leaves links to it as
        # README.html; naming the copy index.md keeps both in step.
        if os.path.basename(page) == "README.md":
            page = os.path.join(os.path.dirname(page), "index.md")
        return page
    return None


def rewrite(text, src, dst):
    def fix(m):
        target = m.group(2)
        if re.match(r"^[a-z]+:", target) or target.startswith("#"):
            return m.group(0)
        path, _, anchor = target.partition("#")
        resolved = os.path.normpath(os.path.join(os.path.dirname(src), path))
        page = staged(resolved) if path.endswith(".md") else None
        if page is not None:
            new = os.path.relpath(page, os.path.dirname(dst))
        else:
            kind = "tree" if os.path.isdir(resolved) else "blob"
            new = f"{REPO}/{kind}/main/{os.path.relpath(resolved, ROOT)}"
        return m.group(1) + new + ("#" + anchor if anchor else "") + m.group(3)

    text = text.split(MARK)[0].rstrip() + "\n"
    return LINK.sub(fix, text)


def main():
    shutil.rmtree(OUT, ignore_errors=True)
    sources = [os.path.join(ROOT, "README.md"), os.path.join(DOCS, "SUMMARY.md")]
    for folder, _, files in os.walk(os.path.join(DOCS, "book")):
        sources += [os.path.join(folder, f) for f in files if f.endswith(".md")]
    for src in sources:
        dst = staged(src)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(src, encoding="utf-8") as f:
            text = f.read()
        with open(dst, "w", encoding="utf-8") as f:
            f.write(rewrite(text, src, dst))
    print(f"staged {len(sources)} pages in {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
